FROM python:3.9
WORKDIR /schedulion-api

COPY ./requirements.txt ./api.py ./.flaskenv ./net-predictor/ ./schedulion-9001-firebase-adminsdk-f5ntk-862c5e8e75.json ./
RUN pip3 install -r ./requirements.txt

EXPOSE 5000
CMD [ "python3", "api.py" ]

# build image for backend:
# docker build -f Dockerfile.api -t schedulion-api .

# create container using image made above:
# docker run -d -t --rm -p 5000:5000 schedulion-api