FROM python:3.9
WORKDIR /schedulion-api

COPY ./requirements.txt ./api.py ./.flaskenv ./net_predictor/ ./firebase_creds.json ./
RUN pip3 install --no-cache-dir -r ./requirements.txt

EXPOSE 5000
# CMD [ "python3", "api.py" ]
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]

# build image for backend:
# docker build -f Dockerfile.api -t schedulion-api .

# create container using image made above:
# docker run -d -t --rm -p 5000:5000 schedulion-api
